# Generated by Django 4.0.4 on 2022-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='caller',
            field=models.CharField(max_length=50),
        ),
    ]
